# Generated by Django 4.2.7 on 2025-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='gallery/images/')),
                ('alt', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('portfolio', 'Portfolio'), ('gallery', 'Gallery'), ('testimonial', 'Testimonial'), ('team', 'Team')], default='gallery', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'gallery_images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
